'use client';

import React, { useState, useEffect } from "react";
import { LogOut, Sun, Moon, UserCircle } from "lucide-react";
import { bin2uuid } from "@/utils/bin2hex";
import { useRouter } from "next/navigation";
import axios from "axios";
import Swal from "sweetalert2";

type DecodedToken = {
  username: string;
  role: string;
  exp: number;
};

export default function Dashboard() {
  const [network, setNetwork] = useState("IMO");
  const [debug, setDebug] = useState("");
  const [modeLink, setModeLink] = useState("hex");
  const [shortURL, setShortURL] = useState("0");
  const [result, setResult] = useState("");
  const [resultShort, setResultShort] = useState("");
  const [darkMode, setDarkMode] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingShort, setIsLoadingShort] = useState(false);

  // Login states
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [user, setUser] = useState<DecodedToken | null>(null);
  const [error, setError] = useState("");
  const router = useRouter();

  // Toggle dark mode
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [darkMode]);

  useEffect(() => {
  async function checkAuth() {
    setIsLoading(true);
    try {
      const res = await axios.get("/api/user/auth");
      if (res.status === 200) {
      const data = res.data;
      if (data.user.role === "member") {
        setUser(data.user);
      } else {
        // Swal for non-member
        if (typeof window !== "undefined") {
        Swal.fire({
          icon: "error",
          title: "Akses Ditolak",
          text: "Hanya member yang bisa mengakses.",
        }).then(() => {
          router.push("/login/user");
        });
        } else {
        router.push("/login/user");
        }
      }
      } else {
      // Swal for failed auth
      if (typeof window !== "undefined") {
        const Swal = (await import("sweetalert2")).default;
        Swal.fire({
        icon: "error",
        title: "Autentikasi Gagal",
        text: "Silakan login ulang.",
        }).then(() => {
        router.push("/login/user");
        });
      } else {
        router.push("/login/user");
      }
      }
    } catch (err: any) {
      // Swal for error
      if (typeof window !== "undefined") {
      const Swal = (await import("sweetalert2")).default;
      Swal.fire({
        icon: "error",
        title: "Terjadi Kesalahan",
        text: "Anda belum login.",
      }).then(() => {
        router.push("/login/user");
      });
      } else {
      router.push("/login/user");
      }
    } finally {
      setIsLoading(false);
    }
  }

  checkAuth();
}, [router]);

  // Handle login
  const handleLogin = async () => {
    setError("");
    try {
      const res = await axios.post("/api/login.user", { username, password });
      // Jika sukses, cookie token sudah otomatis diset server,
      // cukup redirect ke user
      if (res.status === 200) {
        router.push("/");
      }
    } catch (err: any) {
      setError(err.response?.data?.message || err.message || "Login gagal");
    }
  };
  
  // Handle logout
  const logout = async () => {
    await axios.post("/api/user/logout");
    router.push("/login/user");
  };

  const s = (length: number) => {
    const chars = "abcdefghijklmnopqrstuvwxyz";
    return Array.from({ length }, () =>
      chars.charAt(Math.floor(Math.random() * chars.length))
    ).join("");
  };

  const base64UrlEncode = (str: string): string => {
    const rawEncoded = Buffer.from(str).toString('base64');
    const encoded = rawEncoded.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    return encoded.replace(/=/g, '')  // hilangkan padding '='
      .replace(/\+/g, '-') // '+' jadi '-'
      .replace(/\//g, '_'); // '/' jadi '_'
  }

  const strToHex = (str: string) => {
    return [...str]
      .map(c => c.charCodeAt(0).toString(16).padStart(2, '0'))
      .join('');
  }

  const createLink = async () => {
    //return `${s(3)}|${network}|${user?.username}|${s(3)}`;
    return `${user?.username}|${network}|${s(7)}`;
  };

  const generateLink = async () => {
    setIsLoading(true);
    setResultShort(""); // clear short result

    Swal.fire({
      icon: "info",
      title: "Generating Links",
      text: "Please wait while we generate 1000 links...",
      allowOutsideClick: false,
      showConfirmButton: false,
      didOpen: () => {
        Swal.showLoading();
      },
    });

    await new Promise((resolve) => setTimeout(resolve, 10));

    const links: string[] = [];
    const domainList = [
      "facebooke.cam",
      "friendsfb.pro",
      "fwbstars.com",
      "nkmteam.com",
      "setboy.live",
      "smartvids.live",
    ];
    const randomSub = [
          "Adzuki",
          "Adzumi",
          "Adzusa",
          "Aeri",
          "Ageha",
          "Aiha",
          "Aiho",
          "Aika",
          "Aiki",
          "Aiko",
          "Aimi",
          "Aina",
          "Aine",
          "Aino",
          "Aira",
          "Airi",
          "Airu",
          "Aisa",
          "Aise",
          "Aisha",
          "Aito",
          "Aiya",
          "Aiyu",
          "Aka",
          "Akae",
          "Akaho",
          "Akaki",
          "Akana",
          "Akane",
          "Akari",
          "Akatsuki",
          "Akeha",
          "Akeki",
          "Akemi",
          "Akeno",
          "Akeo",
          "Akeyo",
          "Aki",
          "Akie",
          "Akiha",
          "Akiho",
          "Akii",
          "Akika",
          "Akiko",
          "Akime",
          "Akimi",
          "Akina",
          "Akine",
          "Akino",
          "Akira",
          "Akisa",
          "Akiyo",
          "Ako",
          "Akuro",
          "Amarante",
          "Amaya",
          "Ameri",
          "Ami",
          "Amika",
          "Amu",
          "Anan",
          "Anbi",
          "Anda",
          "Aneko",
          "Anji",
          "Anju",
          "Anka",
          "Anmi",
          "Anna",
          "Anne",
          "Anon",
          "Anri",
          "Anru",
          "Ansha",
          "Anzu",
          "Ao",
          "Aoba",
          "Aoha",
          "Aoi",
          "Aoka",
          "Aoki",
          "Aomi",
          "Aona",
          "Aono",
          "Aori",
          "Aose",
          "Aoto",
          "Aozora",
          "Arei",
          "Ari",
          "Arie",
          "Ariha",
          "Ariho",
          "Arika",
          "Arimi",
          "Arin",
          "Arina",
          "Arisa",
          "Arise",
          "Arisu",
          "Arufa",
          "Aruha",
          "Aruna",
          "Asa",
          "Asae",
          "Asagi",
          "Asahi",
          "Asaho",
          "Asai",
          "Asaka",
          "Asaki",
          "Asako",
          "Asami",
          "Asana",
          "Asao",
          "Asara",
          "Asari",
          "Asayo",
          "Asuhi",
          "Asuka",
          "Asumi",
          "Atsue",
          "Atsuka",
          "Atsuki",
          "Atsuko",
          "Atsumi",
          "Atsuna",
          "Atsune",
          "Atsuno",
          "Atsusa",
          "Atsuyo",
          "Awana",
          "Awano",
          "Aya",
          "Ayae",
          "Ayaha",
          "Ayahi",
          "Ayaho",
          "Ayai",
          "Ayaka",
          "Ayaki",
          "Ayako",
          "Ayame",
          "Ayami",
          "Ayamu",
          "Ayana",
          "Ayane",
          "Ayano",
          "Ayao",
          "Ayara",
          "Ayari",
          "Ayasa",
          "Ayase",
          "Ayato",
          "Ayayo",
          "Ayu",
          "Ayuka",
          "Ayuki",
          "Ayume",
          "Ayumi",
          "Ayumu",
          "Ayuna",
          "Ayuno",
          "Ayuri",
          "Ayusa",
          "Ayuto",
          "Azuki",
          "Azumi",
          "Azuna",
          "Azusa",
          "Benten",
          "Biei",
          "Chia",
          "Chiaki",
          "Chiaya",
          "Chidzuki",
          "Chidzuko",
          "Chidzumi",
          "Chidzuru",
          "Chie",
          "Chieko",
          "Chiemi",
          "Chieri",
          "Chigusa",
          "Chiharu",
          "Chihaya",
          "Chihiro",
          "Chiho",
          "Chika",
          "Chikae",
          "Chikage",
          "Chikako",
          "Chikano",
          "Chikara",
          "Chikaru",
          "Chikasa",
          "Chikashi",
          "Chiki",
          "Chiko",
          "Chikoto",
          "Chikuma",
          "China",
          "Chinae",
          "Chinami",
          "Chinari",
          "Chinaru",
          "Chinatsu",
          "Chino",
          "Chinon",
          "Chio",
          "Chiori",
          "Chisa",
          "Chisaki",
          "Chisako",
          "Chisane",
          "Chisato",
          "Chise",
          "Chisei",
          "Chisumi",
          "Chitose",
          "Chiya",
          "Chiyeko",
          "Chiyo",
          "Chiyoko",
          "Chiyomi",
          "Chiyu",
          "Chiyuki",
          "Chiyumi",
          "Chizuru",
          "Cho",
          "Chou",
          "Chura",
          "Dai",
          "Echiko",
          "Ehana",
          "Eho",
          "Ei",
          "Eiha",
          "Eiichi",
          "Eika",
          "Eiko",
          "Eimi",
          "Eina",
          "Eiri",
          "Eko",
          "Ema",
          "Emi",
          "Emiho",
          "Emika",
          "Emiko",
          "Emina",
          "Emio",
          "Emiri",
          "Emu",
          "En",
          "Ena",
          "Eo",
          "Epo",
          "Eran",
          "Ere",
          "Erei",
          "Eren",
          "Erena",
          "Eri",
          "Erika",
          "Eriko",
          "Erin",
          "Erina",
          "Eriya",
          "Eru",
          "Eruna",
          "Eruru",
          "Etsuho",
          "Etsuki",
          "Etsuko",
          "Etsumi",
          "Etsuyo",
          "Euiko",
          "Fua",
          "Fubuki",
          "Fujika",
          "Fujiko",
          "Fujina",
          "Fujino",
          "Fujisa",
          "Fuki",
          "Fumi",
          "Fumie",
          "Fumika",
          "Fumiki",
          "Fumiko",
          "Fumina",
          "Fumino",
          "Fumiyo",
          "Fusa",
          "Fusae",
          "Fusako",
          "Fusana",
          "Fusano",
          "Futaba",
          "Fuu",
          "Fuua",
          "Fuuga",
          "Fuuha",
          "Fuui",
          "Fuuka",
          "Fuuki",
          "Fuuna",
          "Fuune",
          "Fuuno",
          "Fuusa",
          "Fuyu",
          "Fuyue",
          "Fuyuhi",
          "Fuyuka",
          "Fuyuko",
          "Fuyume",
          "Fuyumi",
          "Fuyune",
          "Fuyuno",
          "Fyei",
          "Gemmei",
          "Gen",
          "Gin",
          "Ginko",
          "Gou",
          "Hadzuki",
          "Haine",
          "Haju",
          "Hako",
          "Hama",
          "Hami",
          "Hana",
          "Hanae",
          "Hanaha",
          "Hanaka",
          "Hanako",
          "Hanami",
          "Hanano",
          "Hanari",
          "Hanatsu",
          "Haniko",
          "Hanna",
          "Hano",
          "Hanon",
          "Hanri",
          "Hare",
          "Haru",
          "Harue",
          "Haruha",
          "Haruhi",
          "Haruho",
          "Harui",
          "Haruka",
          "Haruki",
          "Harukichi",
          "Haruko",
          "Haruku",
          "Haruma",
          "Harume",
          "Harumi",
          "Harumo",
          "Harumu",
          "Haruna",
          "Harune",
          "Haruno",
          "Haruo",
          "Haruse",
          "Haruyo",
          "Hase",
          "Hasumi",
          "Hatsue",
          "Hatsuho",
          "Hatsuka",
          "Hatsuki",
          "Hatsuku",
          "Hatsumi",
          "Hatsuna",
          "Hatsune",
          "Hatsuno",
          "Hatsuyo",
          "Haya",
          "Hayaka",
          "Hayami",
          "Hayane",
          "Hayasa",
          "Hayase",
          "Hazumi",
          "Hazuna",
          "Hibiki",
          "Hide",
          "Hideko",
          "Hidemi",
          "Hideri",
          "Hidzuki",
          "Hiho",
          "Hiina",
          "Hiira",
          "Hiiragi",
          "Hiiro",
          "Hiizu",
          "Hikana",
          "Hikari",
          "Hikaru",
          "Himari",
          "Himawari",
          "Hina",
          "Hinagi",
          "Hinaki",
          "Hinako",
          "Hinami",
          "Hinano",
          "Hinari",
          "Hinata",
          "Hinatsu",
          "Hinayo",
          "Hinon",
          "Hiori",
          "Hirari",
          "Hiroa",
          "Hiroe",
          "Hiroha",
          "Hiroka",
          "Hiroko",
          "Hiromi",
          "Hiromu",
          "Hirona",
          "Hirone",
          "Hirono",
          "Hiroo",
          "Hiroshi",
          "Hiroyo",
          "Hisa",
          "Hisae",
          "Hisaho",
          "Hisaka",
          "Hisaki",
          "Hisako",
          "Hisami",
          "Hisana",
          "Hisano",
          "Hisashi",
          "Hisato",
          "Hisayo",
          "Hisui",
          "Hitoe",
          "Hitoha",
          "Hitoka",
          "Hitomi",
          "Hitomo",
          "Hitona",
          "Hitone",
          "Hitono",
          "Hitose",
          "Hitoshi",
          "Hitsuji",
          "Hiyo",
          "Hiyori",
          "Hiyu",
          "Hiyumi",
          "Hodaka",
          "Hodzumi",
          "Hoharu",
          "Hoki",
          "Hona",
          "Honami",
          "Honatsu",
          "Honoka",
          "Honomi",
          "Honon",
          "Honone",
          "Honori",
          "Hoshi",
          "Hoshie",
          "Hoshiha",
          "Hoshiko",
          "Hoshimi",
          "Hoshina",
          "Hoshine",
          "Hoshino",
          "Hoshiyo",
          "Hotaru",
          "Hotona",
          "Hotsumi",
          "Houka",
          "Hozue",
          "Hozumi",
          "Hozumu",
          "Hyuu",
          "Ibuki",
          "Ichi",
          "Ichie",
          "Ichiha",
          "Ichika",
          "Ichimi",
          "Ichina",
          "Ichine",
          "Ichino",
          "Idzumi",
          "Ika",
          "Iku",
          "Ikue",
          "Ikuho",
          "Ikuka",
          "Ikuko",
          "Ikumi",
          "Ikuna",
          "Ikuno",
          "Ikuyo",
          "Imari",
          "Imi",
          "Ina",
          "Inami",
          "Inari",
          "Inatsu",
          "Inori",
          "Inoru",
          "Inoue",
          "Io",
          "Ion",
          "Iori",
          "Ira",
          "Irei",
          "Iri",
          "Irii",
          "Iroha",
          "Iru",
          "Iruka",
          "Isa",
          "Isae",
          "Isaki",
          "Isako",
          "Ise",
          "Isuzu",
          "Ito",
          "Itono",
          "Itsue",
          "Itsuho",
          "Itsuka",
          "Itsuki",
          "Itsuko",
          "Itsumi",
          "Itsuna",
          "Iyo",
          "Iyori",
          "Izuho",
          "Izumi",
          "Jin",
          "Jio",
          "Joruri",
          "Juai",
          "Juan",
          "Juchika",
          "Jue",
          "Juho",
          "Juka",
          "Juki",
          "Jukia",
          "Jun",
          "Juna",
          "June",
          "Junka",
          "Junko",
          "Junmi",
          "Junna",
          "Juno",
          "Junrei",
          "Junri",
          "Jura",
          "Juri",
          "Jurin",
          "Juru",
          "Kaai",
          "Kadzuho",
          "Kadzuki",
          "Kadzumi",
          "Kadzusa",
          "Kae",
          "Kaede",
          "Kagami",
          "Kahana",
          "Kahane",
          "Kaho",
          "Kahori",
          "Kai",
          "Kaida",
          "Kairi",
          "Kaiya",
          "Kaiyo",
          "Kajitsu",
          "Kaju",
          "Kaki",
          "Kako",
          "Kameko",
          "Kami",
          "Kammi",
          "Kammie",
          "Kana",
          "Kanade",
          "Kanae",
          "Kanaha",
          "Kanaho",
          "Kanako",
          "Kaname",
          "Kanami",
          "Kanan",
          "Kanana",
          "Kanari",
          "Kanatsu",
          "Kanawa",
          "Kanayo",
          "Kane",
          "Kaneko",
          "Kanna",
          "Kano",
          "Kanoha",
          "Kanoho",
          "Kanoka",
          "Kanon",
          "Kanori",
          "Kao",
          "Kaon",
          "Kaori",
          "Kaoru",
          "Karan",
          "Karei",
          "Karen",
          "Kari",
          "Karibu",
          "Karin",
          "Karina",
          "Kasaki",
          "Kasane",
          "Kashi",
          "Kasuga",
          "Kasui",
          "Kasumi",
          "Kasune",
          "Kata",
          "Katsue",
          "Katsuki",
          "Katsuko",
          "Katsumi",
          "Kaya",
          "Kayasa",
          "Kayo",
          "Kayoko",
          "Kayou",
          "Kayu",
          "Kayume",
          "Kazu",
          "Kazuchi",
          "Kazue",
          "Kazuha",
          "Kazuhi",
          "Kazuho",
          "Kazuka",
          "Kazuko",
          "Kazumi",
          "Kazuna",
          "Kazune",
          "Kazuno",
          "Kazura",
          "Kazuri",
          "Kazusa",
          "Kazuwo",
          "Kazuyo",
          "Kei",
          "Keiga",
          "Keika",
          "Keiki",
          "Keiko",
          "Keimi",
          "Keina",
          "Keino",
          "Keiri",
          "Keiru",
          "Keisa",
          "Keito",
          "Kia",
          "Kichi",
          "Kichino",
          "Kie",
          "Kifumi",
          "Kiharu",
          "Kihiro",
          "Kiho",
          "Kii",
          "Kiiko",
          "Kiiro",
          "Kika",
          "Kiki",
          "Kiko",
          "Kiku",
          "Kikue",
          "Kikuko",
          "Kikuno",
          "Kikyou",
          "Kimi",
          "Kimie",
          "Kimihi",
          "Kimii",
          "Kimika",
          "Kimiko",
          "Kimina",
          "Kimino",
          "Kimiyo",
          "Kimiyu",
          "Kimu",
          "Kin",
          "Kina",
          "Kinami",
          "Kinatsu",
          "Kino",
          "Kinoka",
          "Kinori",
          "Kinue",
          "Kinuka",
          "Kinuko",
          "Kinumi",
          "Kinuye",
          "Kinuyo",
          "Kioko",
          "Kira",
          "Kiran",
          "Kirara",
          "Kirari",
          "Kiri",
          "Kirika",
          "Kiriko",
          "Kirin",
          "Kirina",
          "Kirine",
          "Kisa",
          "Kisaki",
          "Kisaya",
          "Kisei",
          "Kisha",
          "Kishi",
          "Kishuu",
          "Kita",
          "Kitsuki",
          "Kiwa",
          "Kiya",
          "Kiyo",
          "Kiyoe",
          "Kiyoha",
          "Kiyohi",
          "Kiyoho",
          "Kiyoi",
          "Kiyoka",
          "Kiyoko",
          "Kiyomi",
          "Kiyona",
          "Kiyono",
          "Kiyora",
          "Kiyoshi",
          "Kiyu",
          "Kiyui",
          "Kiyuki",
          "Kiyuu",
          "Kobato",
          "Kochiyo",
          "Kohaku",
          "Kohana",
          "Kohane",
          "Koharu",
          "Kohina",
          "Koi",
          "Koimi",
          "Koiso",
          "Koken",
          "Koko",
          "Kokoa",
          "Kokoe",
          "Kokoha",
          "Kokomi",
          "Kokona",
          "Kokone",
          "Kokori",
          "Kokoro",
          "Kokoru",
          "Komachi",
          "Komaki",
          "Komiki",
          "Komina",
          "Komoe",
          "Komomo",
          "Komugi",
          "Kona",
          "Konami",
          "Konan",
          "Konana",
          "Konatsu",
          "Konoe",
          "Konoha",
          "Konoka",
          "Konoma",
          "Konomi",
          "Korin",
          "Kosato",
          "Kosui",
          "Kosumi",
          "Kosumo",
          "Kosuzu",
          "Koto",
          "Kotoa",
          "Kotoe",
          "Kotoha",
          "Kotoho",
          "Kotoka",
          "Kotoki",
          "Kotoko",
          "Kotome",
          "Kotomi",
          "Kotona",
          "Kotone",
          "Kotono",
          "Kotora",
          "Kotori",
          "Kotose",
          "Kotowa",
          "Kotoyo",
          "Kou",
          "Koue",
          "Kouhi",
          "Kouki",
          "Koumi",
          "Kouna",
          "Koura",
          "Kouran",
          "Kouri",
          "Kousei",
          "Kouyou",
          "Koyori",
          "Koyuki",
          "Koyume",
          "Koyumi",
          "Koyuri",
          "Kozato",
          "Kozue",
          "Kozumi",
          "Kumi",
          "Kumiko",
          "Kuni",
          "Kunie",
          "Kuniko",
          "Kuniyo",
          "Kuno",
          "Kura",
          "Kuran",
          "Kurea",
          "Kureha",
          "Kurei",
          "Kurena",
          "Kureno",
          "Kuri",
          "Kuria",
          "Kuruchi",
          "Kurue",
          "Kurumi",
          "Kyara",
          "Kyoko",
          "Kyou",
          "Kyouka",
          "Kyouki",
          "Kyouko",
          "Kyoumi",
          "Kyouna",
          "Kyoune",
          "Kyouno",
          "Maai",
          "Maasa",
          "Maaya",
          "Mabuki",
          "Machi",
          "Machiko",
          "Madoha",
          "Madoka",
          "Mae",
          "Maeko",
          "Maemi",
          "Mafumi",
          "Mafuyu",
          "Maha",
          "Mahime",
          "Mahiro",
          "Mahiru",
          "Maho",
          "Mahona",
          "Mai",
          "Maia",
          "Maiha",
          "Maiho",
          "Maika",
          "Maiki",
          "Maiko",
          "Maina",
          "Maine",
          "Maino",
          "Maira",
          "Mairi",
          "Maiya",
          "Maka",
          "Makana",
          "Maki",
          "Makie",
          "Makiha",
          "Makiho",
          "Makika",
          "Makiko",
          "Makina",
          "Makino",
          "Makinu",
          "Mako",
          "Makoto",
          "Mami",
          "Mamiko",
          "Mamori",
          "Mana",
          "Manae",
          "Manaha",
          "Manaka",
          "Manako",
          "Manama",
          "Manami",
          "Manan",
          "Manano",
          "Manao",
          "Manare",
          "Manari",
          "Manase",
          "Manato",
          "Manatsu",
          "Manaya",
          "Mane",
          "Mano",
          "Manon",
          "Mao",
          "Maon",
          "Maou",
          "Mara",
          "Mare",
          "Marei",
          "Mareka",
          "Maremu",
          "Maren",
          "Marena",
          "Mari",
          "Maria",
          "Marie",
          "Marika",
          "Mariko",
          "Marin",
          "Marina",
          "Mario",
          "Marisa",
          "Marise",
          "Mariya",
          "Maru",
          "Masae",
          "Masai",
          "Masaki",
          "Masako",
          "Masami",
          "Masana",
          "Masano",
          "Masayo",
          "Mashiho",
          "Masumi",
          "Matsu",
          "Matsuki",
          "Matsuko",
          "Matsumi",
          "Matsuri",
          "Matsuyo",
          "Mau",
          "Maya",
          "Mayaka",
          "Mayako",
          "Mayo",
          "Mayoko",
          "Mayu",
          "Mayue",
          "Mayui",
          "Mayuka",
          "Mayuki",
          "Mayuko",
          "Mayume",
          "Mayumi",
          "Mayumu",
          "Mayuna",
          "Mayura",
          "Mayuri",
          "Mayuu",
          "Mayuzumi",
          "Mebae",
          "Mebuki",
          "Megu",
          "Meguho",
          "Meguka",
          "Megumi",
          "Meguri",
          "Mei",
          "Meika",
          "Meiko",
          "Meina",
          "Meira",
          "Meiran",
          "Meiri",
          "Meiya",
          "Memi",
          "Memori",
          "Mena",
          "Meo",
          "Meya",
          "Meyu",
          "Mia",
          "Miaka",
          "Miaki",
          "Miako",
          "Miasa",
          "Miaya",
          "Mibuki",
          "Michi",
          "Michie",
          "Michiho",
          "Michika",
          "Michiko",
          "Michina",
          "Michio",
          "Michiru",
          "Michiyo",
          "Midori",
          "Midzue",
          "Midzuho",
          "Midzuka",
          "Midzuki",
          "Mie",
          "Miei",
          "Mieko",
          "Mifuki",
          "Mifuu",
          "Mifuyu",
          "Miha",
          "Mihae",
          "Mihana",
          "Mihane",
          "Miharu",
          "Mihato",
          "Mihaya",
          "Mihayu",
          "Mihime",
          "Mihiro",
          "Miho",
          "Mihoka",
          "Mihoko",
          "Mihona",
          "Mii",
          "Miiha",
          "Miiko",
          "Miina",
          "Miine",
          "Miiru",
          "Miju",
          "Mika",
          "Mikae",
          "Mikako",
          "Mikan",
          "Mikana",
          "Mikari",
          "Mikawa",
          "Mikayo",
          "Miki",
          "Mikie",
          "Mikiho",
          "Mikiko",
          "Mikina",
          "Mikino",
          "Mikiyo",
          "Miko",
          "Mikoto",
          "Miku",
          "Mikuho",
          "Mikuka",
          "Miliko",
          "Mima",
          "Mimari",
          "Mimi",
          "Mimori",
          "Mimu",
          "Mina",
          "Minae",
          "Minagi",
          "Minaha",
          "Minaho",
          "Minai",
          "Minaka",
          "Minaki",
          "Minako",
          "Minami",
          "Minamo",
          "Minao",
          "Minari",
          "Minase",
          "Minato",
          "Minatsu",
          "Mine",
          "Mineka",
          "Mineki",
          "Mineko",
          "Mineri",
          "Mino",
          "Minoka",
          "Minoki",
          "Minon",
          "Minori",
          "Minoru",
          "Mio",
          "Mioha",
          "Mioka",
          "Miomi",
          "Mion",
          "Miora",
          "Miori",
          "Mioto",
          "Miou",
          "Mirai",
          "Miran",
          "Mire",
          "Mirei",
          "Miri",
          "Miru",
          "Miruka",
          "Misa",
          "Misaho",
          "Misaki",
          "Misako",
          "Misao",
          "Misato",
          "Misawo",
          "Mishuri",
          "Misono",
          "Misora",
          "Misumi",
          "Misuzu",
          "Mito",
          "Mitsu",
          "Mitsue",
          "Mitsugi",
          "Mitsuha",
          "Mitsuho",
          "Mitsuka",
          "Mitsuki",
          "Mitsuko",
          "Mitsumi",
          "Mitsuna",
          "Mitsune",
          "Mitsuno",
          "Mitsuyo",
          "Miu",
          "Miwa",
          "Miwako",
          "Miwo",
          "Miya",
          "Miyabi",
          "Miyako",
          "Miyano",
          "Miyo",
          "Miyoka",
          "Miyoko",
          "Miyoshi",
          "Miyou",
          "Miyu",
          "Miyuho",
          "Miyuka",
          "Miyuki",
          "Miyumi",
          "Miyusa",
          "Miyuu",
          "Mizue",
          "Mizuha",
          "Mizuho",
          "Mizuka",
          "Mizuki",
          "Mizumi",
          "Mizuna",
          "Mizune",
          "Mizuno",
          "Mizuo",
          "Mizuse",
          "Moa",
          "Moe",
          "Moeka",
          "Moeko",
          "Moemi",
          "Moeno",
          "Moeri",
          "Moi",
          "Moka",
          "Moko",
          "Momi",
          "Momie",
          "Momika",
          "Momo",
          "Momoa",
          "Momoe",
          "Momoha",
          "Momohi",
          "Momoka",
          "Momoki",
          "Momoko",
          "Momoku",
          "Momomi",
          "Momona",
          "Momone",
          "Momono",
          "Momoo",
          "Momose",
          "Momoyo",
          "Mona",
          "Monaka",
          "Monami",
          "Monan",
          "Mone",
          "Mono",
          "Moori",
          "More",
          "Moto",
          "Motoe",
          "Motoi",
          "Motoka",
          "Motoko",
          "Motomi",
          "Mowa",
          "Moyu",
          "Moyumi",
          "Mume",
          "Mura",
          "Muteki",
          "Mutsue",
          "Mutsuka",
          "Mutsuki",
          "Mutsuko",
          "Mutsumi",
          "Mutsuyo",
          "Nachi",
          "Nachie",
          "Nachika",
          "Nadzuki",
          "Nae",
          "Naemi",
          "Naeri",
          "Nagino",
          "Nagisa",
          "Naho",
          "Nahoko",
          "Naina",
          "Naka",
          "Nami",
          "Namie",
          "Namiha",
          "Namiho",
          "Namika",
          "Namiki",
          "Namiko",
          "Namina",
          "Namisa",
          "Namiyo",
          "Nana",
          "Nanae",
          "Nanaha",
          "Nanaho",
          "Nanaka",
          "Nanaki",
          "Nanako",
          "Nanami",
          "Nanan",
          "Nanana",
          "Nanane",
          "Nanao",
          "Nanari",
          "Nanasa",
          "Nanase",
          "Nanashi",
          "Nanato",
          "Nanatsu",
          "Nanaya",
          "Nanka",
          "Nanoha",
          "Nanoka",
          "Nanoko",
          "Nanon",
          "Nanri",
          "Nao",
          "Naoe",
          "Naoha",
          "Naoka",
          "Naoki",
          "Naoko",
          "Naomi",
          "Naon",
          "Naora",
          "Naori",
          "Naren",
          "Nari",
          "Narika",
          "Nariko",
          "Narisa",
          "Naru",
          "Narue",
          "Naruho",
          "Naruka",
          "Narumi",
          "Nasa",
          "Natsu",
          "Natsue",
          "Natsuha",
          "Natsuho",
          "Natsui",
          "Natsuka",
          "Natsuki",
          "Natsuko",
          "Natsume",
          "Natsumi",
          "Natsuna",
          "Natsune",
          "Natsusa",
          "Natsuyo",
          "Nattsu",
          "Nau",
          "Nawa",
          "Naya",
          "Nayo",
          "Nayoko",
          "Nayu",
          "Nayuki",
          "Nayume",
          "Nayumi",
          "Nayura",
          "Nazumi",
          "Nazuna",
          "Neiro",
          "Nemu",
          "Nene",
          "Nera",
          "Neu",
          "Nichika",
          "Nie",
          "Niima",
          "Niina",
          "Niino",
          "Niji",
          "Nijiha",
          "Nijiho",
          "Nijika",
          "Nijina",
          "Niki",
          "Niko",
          "Nina",
          "Nire",
          "Nirei",
          "Nishi",
          "Noa",
          "Nobu",
          "Nobue",
          "Nobuko",
          "Nodoka",
          "Noeru",
          "Noma",
          "Nomi",
          "Nona",
          "Nonka",
          "Nonno",
          "Nono",
          "Nonoka",
          "Nori",
          "Noria",
          "Norie",
          "Noriha",
          "Norika",
          "Noriko",
          "Norina",
          "Norino",
          "Norisa",
          "Norito",
          "Noriyo",
          "Nozomi",
          "Nyoko",
          "Ochiyo",
          "Oharu",
          "Oki",
          "Okichi",
          "Okiku",
          "Omitsu",
          "Omoi",
          "Omoka",
          "Ooaya",
          "Orie",
          "Orika",
          "Orina",
          "Orino",
          "Orisa",
          "Oto",
          "Otoe",
          "Otoha",
          "Otoka",
          "Otona",
          "Otose",
          "Otowa",
          "Otsu",
          "Otsune",
          "Ouka",
          "Oumi",
          "Ouna",
          "Ouri",
          "Pinku",
          "Raichi",
          "Raicho",
          "Raika",
          "Raiki",
          "Raimi",
          "Raina",
          "Raira",
          "Rairi",
          "Raisa",
          "Raito",
          "Raku",
          "Rama",
          "Rami",
          "Ramu",
          "Ran",
          "Rana",
          "Ranan",
          "Ranna",
          "Rara",
          "Rasa",
          "Rea",
          "Reeko",
          "Reemi",
          "Reen",
          "Reena",
          "Reho",
          "Rei",
          "Reia",
          "Reiha",
          "Reiho",
          "Reika",
          "Reiki",
          "Reiko",
          "Reimi",
          "Reina",
          "Reini",
          "Reino",
          "Reira",
          "Reiri",
          "Reisa",
          "Reishi",
          "Reiya",
          "Rema",
          "Remi",
          "Remon",
          "Ren",
          "Rena",
          "Reno",
          "Renon",
          "Reo",
          "Reon",
          "Rera",
          "Reri",
          "Ria",
          "Rian",
          "Ridzu",
          "Ridzuki",
          "Rie",
          "Rieko",
          "Riemi",
          "Riha",
          "Riharu",
          "Riho",
          "Rii",
          "Riju",
          "Rika",
          "Rikako",
          "Rikana",
          "Rikei",
          "Riki",
          "Rikka",
          "Riko",
          "Riku",
          "Rikuka",
          "Rima",
          "Rimi",
          "Rin",
          "Rina",
          "Rinako",
          "Rine",
          "Ringo",
          "Rini",
          "Rinka",
          "Rinna",
          "Rinne",
          "Rino",
          "Rinon",
          "Rio",
          "Rion",
          "Riona",
          "Riori",
          "Rira",
          "Riran",
          "Rirei",
          "Riri",
          "Riria",
          "Ririka",
          "Ririna",
          "Riru",
          "Risa",
          "Risaki",
          "Risako",
          "Risana",
          "Risato",
          "Rise",
          "Risuzu",
          "Rito",
          "Ritsu",
          "Ritsue",
          "Ritsuho",
          "Ritsuki",
          "Ritsuko",
          "Ritsuna",
          "Ritsuno",
          "Riu",
          "Riya",
          "Riyo",
          "Riyu",
          "Riyuu",
          "Riza",
          "Rizu",
          "Rizumu",
          "Romi",
          "Rua",
          "Rubi",
          "Rui",
          "Ruina",
          "Ruiri",
          "Ruka",
          "Ruki",
          "Rumi",
          "Rumiko",
          "Rumoi",
          "Runa",
          "Runmi",
          "Runo",
          "Ruo",
          "Rura",
          "Ruri",
          "Rurika",
          "Ruriko",
          "Ruru",
          "Ruuna",
          "Ruuru",
          "Ryoko",
          "Ryou",
          "Ryoubi",
          "Ryouga",
          "Ryouha",
          "Ryouka",
          "Ryouko",
          "Ryoumi",
          "Ryouna",
          "Ryuubi",
          "Ryuuka",
          "Ryuumi",
          "Ryuuri",
          "Saa",
          "Saaki",
          "Saara",
          "Saari",
          "Saaya",
          "Sachi",
          "Sachie",
          "Sachiho",
          "Sachika",
          "Sachiko",
          "Sachimi",
          "Sachina",
          "Sachino",
          "Sachio",
          "Sachiwo",
          "Sachiyo",
          "Sada",
          "Sadako",
          "Sae",
          "Saeka",
          "Saeko",
          "Saemi",
          "Saera",
          "Saeri",
          "Saharu",
          "Sahi",
          "Saho",
          "Sahoko",
          "Sahori",
          "Sai",
          "Saiha",
          "Saiju",
          "Saika",
          "Saimi",
          "Saira",
          "Sairi",
          "Saisha",
          "Saito",
          "Saka",
          "Sakae",
          "Sakaki",
          "Sakamae",
          "Saki",
          "Sakie",
          "Sakiha",
          "Sakiho",
          "Sakika",
          "Sakiko",
          "Sakimi",
          "Sakimo",
          "Sakina",
          "Sakino",
          "Sakira",
          "Sakisa",
          "Sakiyo",
          "Saku",
          "Sakue",
          "Sakuko",
          "Sakumi",
          "Sakuna",
          "Sakuno",
          "Sakura",
          "Sakurako",
          "Sakuri",
          "Sakuro",
          "Sama",
          "Samasa",
          "Sami",
          "San",
          "Sana",
          "Sanae",
          "Sanako",
          "Sanami",
          "Sanatsu",
          "Sane",
          "Sango",
          "Sano",
          "Sao",
          "Saori",
          "Sara",
          "Sarana",
          "Sarasa",
          "Sari",
          "Sarii",
          "Sarina",
          "Sasa",
          "Sasara",
          "Sasha",
          "Sata",
          "Sato",
          "Satoe",
          "Satoha",
          "Satoho",
          "Satoka",
          "Satoko",
          "Satoma",
          "Satomi",
          "Satona",
          "Satone",
          "Satono",
          "Satori",
          "Satsuka",
          "Satsuki",
          "Satu",
          "Sau",
          "Sawa",
          "Sawae",
          "Sawaka",
          "Sawaki",
          "Sawako",
          "Sawami",
          "Sawayo",
          "Saya",
          "Sayaka",
          "Sayaki",
          "Sayako",
          "Sayami",
          "Sayano",
          "Sayo",
          "Sayoko",
          "Sayomi",
          "Sayori",
          "Sayu",
          "Sayui",
          "Sayuka",
          "Sayuki",
          "Sayumi",
          "Sayuri",
          "Sea",
          "Sei",
          "Seiga",
          "Seiha",
          "Seiho",
          "Seiju",
          "Seika",
          "Seikai",
          "Seiki",
          "Seiko",
          "Seima",
          "Seina",
          "Seine",
          "Seino",
          "Seira",
          "Seiri",
          "Seisa",
          "Seiya",
          "Seka",
          "Seki",
          "Sen",
          "Sena",
          "Senna",
          "Senri",
          "Seo",
          "Sera",
          "Serena",
          "Seri",
          "Seria",
          "Serie",
          "Serika",
          "Serina",
          "Serisa",
          "Seshiru",
          "Setsuka",
          "Setsuko",
          "Seu",
          "Seya",
          "Shidzu",
          "Shidzue",
          "Shidzuka",
          "Shidzuki",
          "Shidzuku",
          "Shidzuru",
          "Shie",
          "Shiemi",
          "Shien",
          "Shieri",
          "Shieru",
          "Shige",
          "Shigeno",
          "Shiho",
          "Shii",
          "Shiimi",
          "Shiina",
          "Shiine",
          "Shiino",
          "Shika",
          "Shiki",
          "Shima",
          "Shimizu",
          "Shina",
          "Shinju",
          "Shinko",
          "Shino",
          "Shinobu",
          "Shinon",
          "Shio",
          "Shioe",
          "Shioi",
          "Shioka",
          "Shiokaze",
          "Shioko",
          "Shiomi",
          "Shion",
          "Shiona",
          "Shiono",
          "Shiora",
          "Shiori",
          "Shiose",
          "Shiou",
          "Shiraho",
          "Shisa",
          "Shisei",
          "Shisumi",
          "Shiun",
          "Shiyono",
          "Shiyori",
          "Shiyou",
          "Shiyu",
          "Shizu",
          "Shizue",
          "Shizuha",
          "Shizuho",
          "Shizuka",
          "Shizuki",
          "Shizuko",
          "Shizuku",
          "Shizuma",
          "Shizumi",
          "Shizuna",
          "Shizuno",
          "Shizuo",
          "Shizura",
          "Shizuri",
          "Shizuru",
          "Shizusa",
          "Shizuse",
          "Shizuto",
          "Shizuyo",
          "Shoka",
          "Shoken",
          "Shoko",
          "Shoon",
          "Shouka",
          "Shouko",
          "Shouna",
          "Shue",
          "Shuho",
          "Shuka",
          "Shuki",
          "Shuma",
          "Shun",
          "Shuna",
          "Shunri",
          "Shunyou",
          "Shura",
          "Shuri",
          "Shusa",
          "Shuu",
          "Shuuha",
          "Shuuho",
          "Shuuka",
          "Shuuki",
          "Shuuko",
          "Shuumi",
          "Shuuna",
          "Soeru",
          "Sona",
          "Sono",
          "Sonoe",
          "Sonoka",
          "Sonoko",
          "Sonomi",
          "Sora",
          "Souka",
          "Soyo",
          "Soyoka",
          "Soyono",
          "Suguri",
          "Sui",
          "Suika",
          "Suki",
          "Suko",
          "Suma",
          "Sumi",
          "Sumie",
          "Sumiha",
          "Sumiho",
          "Sumika",
          "Sumiko",
          "Sumina",
          "Sumino",
          "Sumio",
          "Sumire",
          "Sumiyo",
          "Sumomo",
          "Sunaho",
          "Suzu",
          "Suzue",
          "Suzuha",
          "Suzuho",
          "Suzuka",
          "Suzuki",
          "Suzuko",
          "Suzuma",
          "Suzume",
          "Suzumi",
          "Suzuna",
          "Suzune",
          "Suzuno",
          "Suzuto",
          "Suzuyo",
          "Tadako",
          "Tae",
          "Taeko",
          "Taena",
          "Tai",
          "Taji",
          "Taka",
          "Takae",
          "Takaha",
          "Takako",
          "Takami",
          "Takana",
          "Takane",
          "Takara",
          "Takase",
          "Takayo",
          "Tama",
          "Tamae",
          "Tamafune",
          "Tamaha",
          "Tamahi",
          "Tamaho",
          "Tamai",
          "Tamaka",
          "Tamaki",
          "Tamami",
          "Tamamo",
          "Tamao",
          "Tamara",
          "Tamari",
          "Tamawo",
          "Tamayo",
          "Tami",
          "Tamie",
          "Tamika",
          "Tamiko",
          "Tamiyo",
          "Tanak",
          "Taniko",
          "Tansho",
          "Tao",
          "Tara",
          "Taree",
          "Tatsumi",
          "Taura",
          "Taya",
          "Tenna",
          "Tenri",
          "Tenru",
          "Terue",
          "Teruha",
          "Terumi",
          "Teruna",
          "Teruno",
          "Teruyo",
          "Toa",
          "Tochika",
          "Toka",
          "Toki",
          "Tokie",
          "Tokiha",
          "Tokiko",
          "Tokino",
          "Tokiri",
          "Tokiyo",
          "Toko",
          "Toku",
          "Tokuko",
          "Tomi",
          "Tomie",
          "Tomiko",
          "Tomo",
          "Tomoa",
          "Tomoe",
          "Tomoha",
          "Tomoka",
          "Tomoki",
          "Tomoko",
          "Tomomi",
          "Tomona",
          "Tomone",
          "Tomono",
          "Tomoo",
          "Tomose",
          "Tomoyo",
          "Tona",
          "Tonami",
          "Tono",
          "Toomi",
          "Toon",
          "Tooru",
          "Toshi",
          "Toshie",
          "Toshika",
          "Toshiko",
          "Toshimi",
          "Toshino",
          "Toshiyo",
          "Touka",
          "Toumi",
          "Touna",
          "Towa",
          "Toya",
          "Toyoko",
          "Tsubame",
          "Tsubasa",
          "Tsue",
          "Tsugumi",
          "Tsuguri",
          "Tsukasa",
          "Tsuki",
          "Tsukiyama",
          "Tsukumi",
          "Tsuneko",
          "Tsutae",
          "Tsutako",
          "Tsuya",
          "Ubuka",
          "Ui",
          "Uika",
          "Ume",
          "Umeka",
          "Umeko",
          "Umi",
          "Umie",
          "Umina",
          "Una",
          "Uno",
          "Urako",
          "Uran",
          "Urara",
          "Urei",
          "Uru",
          "Urue",
          "Uruha",
          "Urume",
          "Urumi",
          "Ururu",
          "Usa",
          "Usagi",
          "Ushio",
          "Uta",
          "Utae",
          "Utaha",
          "Utaka",
          "Utako",
          "Utami",
          "Utano",
          "Utayo",
          "Utsuki",
          "Uyo",
          "Waka",
          "Wakaba",
          "Wakae",
          "Wakaha",
          "Wakaho",
          "Wakako",
          "Wakami",
          "Wakana",
          "Wakano",
          "Wakao",
          "Wattan",
          "Waya",
          "Wayu",
          "Wazuka",
          "Yachi",
          "Yae",
          "Yaeko",
          "Yaemi",
          "Yama",
          "Yasu",
          "Yasue",
          "Yasuha",
          "Yasuho",
          "Yasuka",
          "Yasuki",
          "Yasuko",
          "Yasumi",
          "Yasuna",
          "Yasuno",
          "Yasuo",
          "Yasura",
          "Yasuyo",
          "Yayoi",
          "Yayori",
          "Yazuya",
          "Yodo",
          "Yoko",
          "Yomishi",
          "Yomogi",
          "Yori",
          "Yorie",
          "Yorika",
          "Yoriko",
          "Yorimi",
          "Yorina",
          "Yoshe",
          "Yoshi",
          "Yoshie",
          "Yoshiho",
          "Yoshika",
          "Yoshike",
          "Yoshiki",
          "Yoshiko",
          "Yoshimi",
          "Yoshina",
          "Yoshine",
          "Yoshino",
          "Yoshiri",
          "You",
          "Youju",
          "Youka",
          "Youko",
          "Youna",
          "Yousei",
          "Yu",
          "Yua",
          "Yuami",
          "Yuan",
          "Yuara",
          "Yuari",
          "Yuasa",
          "Yuchika",
          "Yudzuha",
          "Yudzuki",
          "Yudzuru",
          "Yue",
          "Yuei",
          "Yufu",
          "Yuhana",
          "Yuhaya",
          "Yuhiro",
          "Yuho",
          "Yui",
          "Yuiga",
          "Yuiha",
          "Yuiho",
          "Yuika",
          "Yuiki",
          "Yuiko",
          "Yuina",
          "Yuine",
          "Yuiri",
          "Yuisa",
          "Yuka",
          "Yukako",
          "Yukana",
          "Yukari",
          "Yukayo",
          "Yuki",
          "Yukia",
          "Yukie",
          "Yukiha",
          "Yukiho",
          "Yukika",
          "Yukiko",
          "Yukimi",
          "Yukina",
          "Yukine",
          "Yukino",
          "Yukio",
          "Yukisa",
          "Yukise",
          "Yukiyo",
          "Yuko",
          "Yuma",
          "Yumako",
          "Yume",
          "Yumeha",
          "Yumeho",
          "Yumeka",
          "Yumemi",
          "Yumena",
          "Yumeri",
          "Yumeto",
          "Yumi",
          "Yumie",
          "Yumika",
          "Yumiko",
          "Yumina",
          "Yumine",
          "Yumino",
          "Yumio",
          "Yumiyo",
          "Yuna",
          "Yune",
          "Yuni",
          "Yuno",
          "Yunoka",
          "Yunon",
          "Yuo",
          "Yuori",
          "Yura",
          "Yuri",
          "Yuriha",
          "Yurika",
          "Yuriko",
          "Yurima",
          "Yusa",
          "Yusana",
          "Yusato",
          "Yusuke",
          "Yuto",
          "Yutsuki",
          "Yutsuru",
          "Yuu",
          "Yuua",
          "Yuuga",
          "Yuuha",
          "Yuuhi",
          "Yuuho",
          "Yuui",
          "Yuuka",
          "Yuuki",
          "Yuuko",
          "Yuumi",
          "Yuuna",
          "Yuuno",
          "Yuuri",
          "Yuusa",
          "Yuuwa",
          "Yuuyu",
          "Yuya",
          "Yuyu",
          "Yuzu",
          "Yuzuha",
          "Yuzuho",
          "Yuzuka",
          "Yuzuki",
          "Yuzumi",
          "Yuzuru",
          "Yuzusa"
    ];

    for (let i = 0; i < 1000; i++) {
      let link = "";
      let selectedDomain = shortURL === "0"
      ? domainList[Math.floor(Math.random() * domainList.length)]
      : shortURL;
      let subDomain = randomSub[Math.floor(Math.random() * randomSub.length)].toLowerCase();
      let subDomain2 = randomSub[Math.floor(Math.random() * randomSub.length)].toLowerCase();
      if (modeLink === "hex") {
        const linkStr = await createLink();
        link = `${debug}https://${subDomain+subDomain2}.${selectedDomain}/${strToHex(linkStr)}`;
      } else if (modeLink === "binary") {
        const linkStr = await createLink();
        link = `${debug}https://${subDomain+subDomain2}.${selectedDomain}/${bin2uuid(linkStr)}`;
      } else if (modeLink === "base64") {
        const linkStr = await createLink();
        const linkBytes = new TextEncoder().encode(linkStr);
        link = `${debug}https://${subDomain+subDomain2}.${selectedDomain}/${base64UrlEncode(String.fromCharCode(...linkBytes))}`;
      }
      links.push(link);
    }

    setResult(links.join("\n")); // gabungkan semua link dengan newline
    setIsLoading(false);

    Swal.fire({
      icon: "success",
      title: "Links Generated",
      text: "Successfully generated 1000 links.",
    });
  };

  const shortLink = async () => {
    setIsLoadingShort(true);

    try {
      const { data } = await axios.post("/api/short", {
        url: `${encodeURIComponent(`${debug}https://localhost:3000/${bin2uuid(await createLink())}`)}`,
        opt: "0", // atau sesuai kebutuhan
      });

      Swal.fire({
        icon: "success",
        title: "Shortlink Created",
        text: data.shorturl || "Berhasil",
      });
    } catch (err: any) {
      console.error(err);
      Swal.fire({
        icon: "error",
        title: "Shortlink Failed",
        text: err.response?.data?.message || "Unknown error",
      });
    } finally {
      setIsLoadingShort(false);
    }
  };

  // LOGIN FORM
  if (!user) {
    return (
      <div className="min-h-screen flex flex-col justify-center items-center bg-gray-100 dark:bg-gray-900 p-6">
        <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-md w-full max-w-md">
          <h2 className="text-2xl font-semibold mb-6 text-gray-900 dark:text-gray-100">
            Login Member
          </h2>
          <input
            type="text"
            placeholder="Username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="w-full mb-4 p-3 rounded border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          />
          <input
            type="password"
            placeholder="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full mb-4 p-3 rounded border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          />
          {error && (
            <p className="text-red-600 mb-4 text-sm">{error}</p>
          )}
          <button
            onClick={handleLogin}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded transition"
          >
            Login
          </button>
        </div>
      </div>
    );
  }

  // DASHBOARD
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 flex flex-col items-center p-6">
      {/* Topbar */}
      <div className="w-full max-w-xl flex justify-between items-center bg-white dark:bg-gray-800 shadow-md p-4 rounded-xl mb-4">
        <div className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
          <UserCircle className="w-5 h-5 text-blue-500" />
          <span className="font-serif truncate max-w-[150px]">{user.username}</span>
        </div>
        <div className="flex items-center space-x-6">
          <button
            onClick={() => setDarkMode(!darkMode)}
            aria-label="Toggle Dark Mode"
            className="p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
          >
            {darkMode ? <Sun className="text-yellow-400" /> : <Moon className="text-gray-600" />}
          </button>
          <button
            onClick={logout}
            className="flex items-center text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-600"
          >
            <LogOut className="w-5 h-5 mr-1" />
            
          </button>
        </div>
      </div>

      {/* Option Links */}
      <div className="w-full max-w-xl bg-white dark:bg-gray-800 shadow-md rounded-xl p-6 flex flex-wrap md:flex-nowrap items-center gap-4">
        <div className="flex flex-col min-w-[150px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Network
          </label>
          <select
            value={network}
            onChange={(e) => setNetwork(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          >
            <option value="IMO">iMonetizeIt</option>
            <option value="TF">Trafee</option>
            <option value="LP">Lospollos</option>
          </select>
        </div>

        {/* Debug Option */}
        <div className="flex flex-col min-w-[150px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Debugger
          </label>
          <select
            value={debug}
            onChange={(e) => setDebug(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          >
            <option value="">---</option>
            <option value="https://l.wl.co/l?u=">l.wl.co</option>
          </select>
        </div>

        {/* Button short! */}
        <div className="flex flex-col justify-end min-w-[150px]">
          <label className="invisible mb-1">Action</label>
          <button
            onClick={generateLink}
            disabled={isLoading}
            className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg transition-colors whitespace-nowrap w-full"
          >
            {isLoading ? "Getting Link..." : "Get Link"}
          </button>
        </div>
      </div>

      {/* Option Link */}
      <div className="w-full max-w-xl bg-white dark:bg-gray-800 shadow-md rounded-xl p-6 flex flex-wrap md:flex-nowrap items-center gap-4 mt-4">
        {/* Domain */}
        <div className="flex flex-col min-w-[160px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Domain
          </label>
            <select
            value={shortURL}
            onChange={(e) => setShortURL(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
            >
            <option value="0">{'{RANDOM GLOBAL DOMAIN}'}</option>
            <option value="facebooke.cam">facebooke.cam</option>
            <option value="friendsfb.pro">friendsfb.pro</option>
            <option value="fwbstars.com">fwbstars.com</option>
            <option value="nkmteam.com">nkmteam.com</option>
            <option value="setboy.live">setboy.live</option>
            <option value="smartvids.live">smartvids.live</option>
            </select>
        </div>

        {/* Mode Link */}
        <div className="flex flex-col min-w-[200px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Mode Link
          </label>
          <select
            value={modeLink}
            onChange={(e) => setModeLink(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          >
            <option value="hex">hex</option>
            <option disabled value="binary">binary</option>
            <option disabled value="base64">base64</option>
          </select>
        </div>

      </div>

      {/* Short URL */}
      <div hidden className="w-full max-w-xl bg-white dark:bg-gray-800 shadow-md rounded-xl p-6 flex flex-wrap md:flex-nowrap items-center gap-4 mt-4">
        {/* Opsi Shortener */}
        <div className="flex flex-col min-w-[160px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Shortener
          </label>
            <select
            value={shortURL}
            onChange={(e) => setShortURL(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
            >
            <option value="0">is.gd</option>
            <option value="1">u.to</option>
            </select>
        </div>

        {/* Opsi Debugger */}
        <div className="flex flex-col min-w-[160px]">
          <label className="mb-1 text-gray-700 dark:text-gray-300 font-medium">
            Debugger
          </label>
          <select
            value={debug}
            onChange={(e) => setDebug(e.target.value)}
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
          >
            <option value="https://l.wl.co/l?u=">l.wl.co</option>
            <option value="">---</option>
          </select>
        </div>

        {/* Tombol Short */}
        <div className="flex flex-col justify-end min-w-[120px]">
          <label className="invisible mb-1">Action</label>
          <button
            onClick={shortLink}
            disabled={isLoadingShort}
            className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg transition-colors whitespace-nowrap w-full"
          >
            {isLoadingShort ? "Shortening..." : "Short"}
          </button>
        </div>
      </div>

      {/* Result - Show whichever is latest */}
      <div className="w-full max-w-xl bg-white dark:bg-gray-800 shadow-md rounded-xl p-6 mt-4">
        <label className="block mb-2 text-gray-700 dark:text-gray-300 font-medium">
          Generated Link
        </label>
        <textarea
          wrap="off"
          value={result || resultShort || ""}
          readOnly
          rows={4}
          onClick={() => {
            navigator.clipboard.writeText(result || resultShort || "");
            Swal.fire({
              icon: "success",
              title: "Copied to Clipboard",
              text: "Link has been copied to clipboard.",
            });
          }}
          className="w-full p-3 rounded-md bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100 resize-none border-0"
          placeholder="Hasil link akan muncul di sini..."
        />
      </div>

      {/* Footer */}
      <footer className="mt-6 text-gray-500 dark:text-gray-400">
        <p>Powered by ZDEV &copy; 2025 All rights reserved.</p>
      </footer>
    </div>
  );

}
